default_context:
  project_name: 'FranzXaver'
  project_slug: 'franzxaver'
  domain_main: 'franzxaver.holloway.ai'
  domain_staging: 'stag.franzxaver.holloway.ai'
  docker_swarm_stack_name_main: 'franzxaver-holloway-ai'
  docker_swarm_stack_name_staging: 'stag-franzxaver-holloway-ai'
  secret_key: 'c8a526360a9855157042e52c67529a3651a48f7052a0b101fb1c4f87ef779e23'
  first_superuser: 'admin@franzxaver.holloway.ai'
  first_superuser_password: 'VcVNA/kA+553YWFDuRZqGw'
  backend_cors_origins: '["http://localhost", "http://localhost:4200", "http://localhost:3000", "http://localhost:8080", "https://localhost", "https://localhost:4200", "https://localhost:3000", "https://localhost:8080", "http://dev.franzxaver.holloway.ai", "https://stag.franzxaver.holloway.ai", "https://franzxaver.holloway.ai", "http://local.dockertoolbox.tiangolo.com", "http://localhost.tiangolo.com"]'
  smtp_port: '587'
  smtp_host: ''
  smtp_user: ''
  smtp_password: ''
  smtp_emails_from_email: 'info@franzxaver.holloway.ai'
  postgres_password: 'VERUsFthrnFSXA0NsU+nnQ'
  pgadmin_default_user: 'admin@franzxaver.holloway.ai'
  pgadmin_default_user_password: 'VcVNA/kA+553YWFDuRZqGw'
  traefik_constraint_tag: 'franzxaver.holloway.ai'
  traefik_constraint_tag_staging: 'stag.franzxaver.holloway.ai'
  traefik_public_constraint_tag: 'traefik-public'
  flower_auth: 'admin:VcVNA/kA+553YWFDuRZqGw'
  sentry_dsn: ''
  docker_image_prefix: 'ghcr.io/holloway-ai/'
  docker_image_backend: 'ghcr.io/holloway-ai/franzxaver-api'
  docker_image_celeryworker: 'ghcr.io/holloway-ai/franzxaver-worker'
  docker_image_frontend: 'ghcr.io/holloway-ai/franzxaver-app'
  _copy_without_render: [frontend/src/**/*.html, frontend/src/**/*.vue, frontend/node_modules/*, backend/app/app/email-templates/**]
  _template: ./
